# Generated by Django 6.0.2 on 2026-07-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('link', models.CharField(max_length=200, verbose_name='آدرس')),
                ('icon', models.CharField(choices=[('bi-house', 'خانه'), ('bi-book', 'کتاب'), ('bi-grid', 'دسته\u200cبندی'), ('bi-newspaper', 'مقالات'), ('bi-info-circle', 'درباره ما'), ('bi-envelope', 'تماس با ما'), ('bi-person', 'پروفایل'), ('bi-gear', 'تنظیمات'), ('bi-search', 'جستجو'), ('bi-tag', 'برچسب'), ('bi-star', 'ستاره'), ('bi-heart', 'قلب'), ('bi-clock', 'زمان'), ('bi-calendar', 'تقویم'), ('bi-chat', 'چت'), ('bi-bell', 'زنگ'), ('bi-cart', 'سبد خرید'), ('bi-credit-card', 'کارت اعتباری'), ('bi-gift', 'هدیه'), ('bi-rocket', 'موشک'), ('bi-lightbulb', 'لامپ'), ('bi-camera', 'دوربین'), ('bi-music-note', 'موسیقی'), ('bi-video', 'ویدیو'), ('bi-file-text', 'فایل متنی'), ('bi-folder', 'پوشه'), ('bi-download', 'دانلود'), ('bi-upload', 'آپلود'), ('bi-share', 'اشتراک\u200cگذاری'), ('bi-link', 'لینک'), ('bi-lock', 'قفل'), ('bi-unlock', 'باز کردن قفل'), ('bi-key', 'کلید'), ('bi-pencil', 'مداد'), ('bi-trash', 'سطل زباله'), ('bi-plus', 'افزودن'), ('bi-minus', 'حذف'), ('bi-check', 'تأیید'), ('bi-x', 'انصراف'), ('bi-arrow-right', 'فلش راست'), ('bi-arrow-left', 'فلش چپ'), ('bi-arrow-up', 'فلش بالا'), ('bi-arrow-down', 'فلش پایین'), ('bi-chevron-right', 'چپ\u200cگرد راست'), ('bi-chevron-left', 'چپ\u200cگرد چپ'), ('bi-chevron-up', 'چپ\u200cگرد بالا'), ('bi-chevron-down', 'چپ\u200cگرد پایین'), ('bi-globe', 'جهان'), ('bi-map', 'نقشه'), ('bi-phone', 'تلفن'), ('bi-laptop', 'لپ\u200cتاپ'), ('bi-tablet', 'تبلت'), ('bi-phone-landscape', 'تلفن افقی'), ('bi-display', 'نمایشگر'), ('bi-server', 'سرور'), ('bi-cloud', 'ابر'), ('bi-database', 'پایگاه داده'), ('bi-code', 'کد'), ('bi-terminal', 'ترمینال'), ('bi-bug', 'بگ'), ('bi-shield', 'سپر'), ('bi-shield-lock', 'سپر قفل'), ('bi-shield-check', 'سپر تأیید'), ('bi-eye', 'چشم'), ('bi-eye-slash', 'چشم بسته'), ('bi-brightness-high', 'روشنایی بالا'), ('bi-brightness-low', 'روشنایی پایین'), ('bi-moon', 'ماه'), ('bi-sun', 'خورشید'), ('bi-cloud-sun', 'ابر و خورشید'), ('bi-cloud-moon', 'ابر و ماه'), ('bi-cloud-rain', 'ابر بارانی'), ('bi-cloud-snow', 'ابر برفی'), ('bi-wind', 'باد'), ('bi-snow', 'برف'), ('bi-thermometer', 'دماسنج'), ('bi-droplet', 'قطره'), ('bi-droplet-half', 'نصف قطره'), ('bi-bar-chart', 'نمودار میله\u200cای'), ('bi-pie-chart', 'نمودار دایره\u200cای'), ('bi-line-chart', 'نمودار خطی'), ('bi-activity', 'فعالیت'), ('bi-heart-pulse', 'ضربان قلب'), ('bi-cpu', 'پردازنده'), ('bi-memory', 'حافظه'), ('bi-hdd', 'هارد دیسک'), ('bi-sd-card', 'کارت حافظه'), ('bi-sim', 'سیم کارت'), ('bi-usb', 'یواس\u200cبی'), ('bi-bluetooth', 'بلوتوث'), ('bi-wifi', 'وای\u200cفای'), ('bi-headphones', 'هدفون'), ('bi-speaker', 'بلندگو'), ('bi-mic', 'میکروفون'), ('bi-mic-mute', 'میکروفون خاموش'), ('bi-play', 'پخش'), ('bi-pause', 'مکث'), ('bi-stop', 'توقف'), ('bi-skip-forward', 'جلو'), ('bi-skip-backward', 'عقب'), ('bi-shuffle', 'تصادفی'), ('bi-repeat', 'تکرار'), ('bi-zoom-in', 'بزرگ\u200cنمایی'), ('bi-zoom-out', 'کوچک\u200cنمایی'), ('bi-fullscreen', 'تمام صفحه'), ('bi-fullscreen-exit', 'خروج از تمام صفحه'), ('bi-crop', 'برش'), ('bi-rotate-left', 'چرخش به چپ'), ('bi-rotate-right', 'چرخش به راست'), ('bi-flip-horizontal', 'چرخش افقی'), ('bi-flip-vertical', 'چرخش عمودی'), ('bi-align-start', 'تراز شروع'), ('bi-align-center', 'تراز وسط'), ('bi-align-end', 'تراز پایان'), ('bi-align-top', 'تراز بالا'), ('bi-align-middle', 'تراز وسط عمودی'), ('bi-align-bottom', 'تراز پایین'), ('bi-justify', 'هم\u200cتراز'), ('bi-text-left', 'متن چپ'), ('bi-text-center', 'متن وسط'), ('bi-text-right', 'متن راست'), ('bi-bold', 'پررنگ'), ('bi-italic', 'کج'), ('bi-underline', 'زیرخط'), ('bi-strikethrough', 'خط\u200cخورده'), ('bi-fonts', 'فونت\u200cها'), ('bi-type', 'نوع'), ('bi-quote', 'نقل قول'), ('bi-list', 'لیست'), ('bi-list-ol', 'لیست شماره\u200cدار'), ('bi-list-ul', 'لیست گلوله\u200cای'), ('bi-check-all', 'تأیید همه'), ('bi-check-circle', 'دایره تأیید'), ('bi-check-circle-fill', 'دایره تأیید پر'), ('bi-check-square', 'مربع تأیید'), ('bi-check-square-fill', 'مربع تأیید پر'), ('bi-x-circle', 'دایره انصراف'), ('bi-x-circle-fill', 'دایره انصراف پر'), ('bi-x-square', 'مربع انصراف'), ('bi-x-square-fill', 'مربع انصراف پر'), ('bi-plus-circle', 'دایره افزودن'), ('bi-plus-circle-fill', 'دایره افزودن پر'), ('bi-plus-square', 'مربع افزودن'), ('bi-plus-square-fill', 'مربع افزودن پر'), ('bi-dash-circle', 'دایره حذف'), ('bi-dash-circle-fill', 'دایره حذف پر'), ('bi-dash-square', 'مربع حذف'), ('bi-dash-square-fill', 'مربع حذف پر'), ('bi-exclamation-circle', 'دایره هشدار'), ('bi-exclamation-circle-fill', 'دایره هشدار پر'), ('bi-exclamation-triangle', 'مثلث هشدار'), ('bi-exclamation-triangle-fill', 'مثلث هشدار پر'), ('bi-question-circle', 'دایره سوال'), ('bi-question-circle-fill', 'دایره سوال پر'), ('bi-question-square', 'مربع سوال'), ('bi-question-square-fill', 'مربع سوال پر'), ('bi-info-circle', 'دایره اطلاعات'), ('bi-info-circle-fill', 'دایره اطلاعات پر'), ('bi-info-square', 'مربع اطلاعات'), ('bi-info-square-fill', 'مربع اطلاعات پر')], default='bi-link', help_text='آیکون\u200cهای Bootstrap Icons را انتخاب کنید', max_length=50, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='در تب جدید باز شود')),
            ],
            options={
                'verbose_name': 'گزینه نوبار',
                'verbose_name_plural': 'گزینه\u200cهای نوبار',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=100, unique=True, verbose_name='نام تنظیمات')),
                ('setting_value', models.TextField(verbose_name='مقدار تنظیمات')),
                ('site_name', models.CharField(default='پیک لرن', max_length=100, verbose_name='نام سایت')),
                ('site_description', models.TextField(blank=True, verbose_name='توضیحات سایت')),
                ('site_logo', models.ImageField(blank=True, help_text='لوگو سایت (فرمت\u200cهای مجاز: PNG, JPG, SVG)', null=True, upload_to='site_logos/', verbose_name='لوگو سایت')),
                ('site_icon', models.ImageField(blank=True, help_text='آیکون سایت برای مرورگر (اندازه پیشنهادی: 32x32 یا 64x64 پیکسل)', null=True, upload_to='site_icons/', verbose_name='آیکون سایت (Favicon)')),
                ('site_favicon', models.ImageField(blank=True, help_text='آیکون برای تب مرورگر (16x16 یا 32x32 پیکسل)', null=True, upload_to='favicons/', verbose_name='Favicon')),
                ('primary_color', models.CharField(default='#FFD54A', help_text='رنگ اصلی سایت (مثلاً #FFD54A)', max_length=7, verbose_name='رنگ اصلی')),
                ('secondary_color', models.CharField(default='#2563EB', help_text='رنگ ثانویه سایت (مثلاً #2563EB)', max_length=7, verbose_name='رنگ ثانویه')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان متا')),
                ('meta_description', models.TextField(blank=True, verbose_name='توضیحات متا')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, verbose_name='کلمات کلیدی')),
                ('meta_author', models.CharField(blank=True, max_length=100, verbose_name='نویسنده')),
                ('social_instagram', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('social_telegram', models.URLField(blank=True, verbose_name='تلگرام')),
                ('social_twitter', models.URLField(blank=True, verbose_name='توییتر')),
                ('social_linkedin', models.URLField(blank=True, verbose_name='لینکدین')),
                ('social_youtube', models.URLField(blank=True, verbose_name='یوتیوب')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل تماس')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
                'ordering': ['-created_at'],
            },
        ),
    ]
