# Generated by Django 6.0.2 on 2026-07-05 11:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب')),
                ('is_free', models.BooleanField(default=False, verbose_name='رایگان')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='پیشرفت')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اتمام')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام',
                'verbose_name_plural': 'ثبت\u200cنام\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CourseFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='متن')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'پیش\u200cنیاز',
                'verbose_name_plural': 'پیش\u200cنیازها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('file', models.FileField(blank=True, null=True, upload_to='course_resources', verbose_name='فایل')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Document'), ('zip', 'ZIP'), ('link', 'لینک'), ('other', 'سایر')], default='pdf', max_length=10, verbose_name='نوع منبع')),
                ('is_free', models.BooleanField(default=False, verbose_name='رایگان')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'منبع',
                'verbose_name_plural': 'منابع',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='امتیاز')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_approved', models.BooleanField(default=True, verbose_name='تایید شده')),
            ],
            options={
                'verbose_name': 'نظر دوره',
                'verbose_name_plural': 'نظرات دوره',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='LearnPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='متن')),
                ('icon', models.CharField(default='bi-check-circle-fill', max_length=50, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'نکته آموزشی',
                'verbose_name_plural': 'نکات آموزشی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('last_watched', models.DateTimeField(auto_now=True, verbose_name='آخرین بازدید')),
                ('watch_time', models.DurationField(default=datetime.timedelta(0), verbose_name='زمان تماشا')),
            ],
            options={
                'verbose_name': 'پیشرفت کاربر',
                'verbose_name_plural': 'پیشرفت کاربران',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('url', models.URLField(verbose_name='آدرس ویدیو')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=300), verbose_name='مدت زمان')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب')),
                ('is_free_preview', models.BooleanField(default=False, verbose_name='پیش\u200cنمایش رایگان')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='video_attachments', verbose_name='فایل پیوست')),
                ('attachment_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام فایل پیوست')),
                ('is_downloadable', models.BooleanField(default=False, verbose_name='قابل دانلود')),
            ],
            options={
                'verbose_name': 'ویدئو',
                'verbose_name_plural': 'ویدئوها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'علاقه\u200cمندی',
                'verbose_name_plural': 'علاقه\u200cمندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='آیکون')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='اسلاگ')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='courses.category', verbose_name='دسته ی مادر')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='اسلاگ')),
                ('thumbnail', models.FileField(upload_to='course_thumbnails', verbose_name='تصویر دوره')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='course_covers', verbose_name='تصویر کاور')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('short_description', models.TextField(default='', max_length=300, verbose_name='توضیحات کوتاه')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت تخفیف')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='مدت زمان')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], default='beginner', max_length=20, verbose_name='سطح دشواری')),
                ('language', models.CharField(choices=[('fa', 'فارسی'), ('en', 'انگلیسی')], default='fa', max_length=10, verbose_name='زبان')),
                ('has_certificate', models.BooleanField(default=False, verbose_name='گواهینامه دارد')),
                ('certificate_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='متن گواهینامه')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('status', models.CharField(choices=[('published', 'منتشر شده'), ('draft', 'پیش نویس')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره ها',
                'ordering': ['-created_date'],
            },
        ),
    ]
