# Generated by Django 6.0.2 on 2026-07-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseReview',
        ),
    ]
