# Generated by Django 6.0.2 on 2026-07-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_delete_coursereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='completion_status',
            field=models.CharField(choices=[('watched', 'Watched'), ('not_watched', 'Not Watched')], default='not_watched', max_length=11, verbose_name='وضعیت'),
        ),
    ]
