# Generated by Django 6.0.2 on 2026-07-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='blog_comment_blog_appr_idx',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
