# Generated by Django 6.0.2 on 2026-10-07 05:25

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_comment_blog_comment_blog_appr_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='محتوا'),
        ),
    ]
