# Generated by Django 6.0.2 on 2026-10-07 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان سری')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سری مقالات',
                'verbose_name_plural': 'سری\u200cهای مقالات',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='series_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب در سری'),
        ),
        migrations.AddField(
            model_name='blog',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.series', verbose_name='سری مقالات'),
        ),
    ]
