# Generated by Django 6.0.2 on 2026-07-07 06:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('completed', 'موفق'), ('pending', 'در انتظار پرداخت'), ('failed', 'ناموفق'), ('refunded', 'بازگشت وجه')], default='completed', max_length=10, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='transaction_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
