# Generated by Django 6.0.2 on 2026-07-06 09:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reviews', '0003_alter_review_options_remove_review_review_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='reviews_review_unique_user_course',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_review_course_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_approved_idx',
            old_name='reviews_review_approved_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_created_idx',
            old_name='reviews_review_created_idx',
        ),
        migrations.AddField(
            model_name='review',
            name='content_type',
            field=models.ForeignKey(default=1, limit_choices_to={'model__in': ['course', 'blog']}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='contenttypes.contenttype', verbose_name='نوع محتوا'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='object_id',
            field=models.PositiveIntegerField(default=1, verbose_name='شناسه محتوا'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.review', verbose_name='پاسخ به'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='عددی بین ۱ تا ۵', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['content_type', 'object_id'], name='reviews_content_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='reviews_unique_user_content'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='course',
        ),
    ]
